---
output: github_document
---

```{r, include = FALSE}

knitr::opts_chunk$set(
  collapse=TRUE,
  comment="#>",
  out.width="100%"
)

options(
  tibble.print_min=5, 
  tibble.print_max=5,
  width=80
)

```

# get_replies_delegates

## Overview

Scripts that can be used to collect all Twitter coversations started by members of the US congress. The replies are collected via the [standard search (Version 1.1)](https://developer.twitter.com/en/docs/twitter-api/v1/tweets/search/api-reference/get-search-tweets) API endpoint. As my access to historical data through this API enpoint is limited to the past ~7 days, the script has to be executed repeatedly.

## ...

```{r, message=FALSE}

library(tidyverse)

dir_data <- fs::dir_create("~/Documents/get_tweets/data")

tweets_db <- DBI::dbConnect(
  drv=RSQLite::SQLite(), 
  dbname=fs::path(dir_data, "tweets", ext="db"),
  extended_types=TRUE
)

DBI::dbListTables(tweets_db)

```


```{r}

tbl(tweets_db, "tweets_raw")

pull(tally(tbl(tweets_db, "tweets_raw")), n)

tbl(tweets_db, "tweets_raw") %>% 
  group_by(lubridate::as_date(tweet_created_at)) %>% 
  summarise(count = n()) %>% 
  collect()

```


